site_name: GCES- Tainacan
repo_url: https://github.com/
repo_name: GCES- Tainacan

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Atas:
    - Ata 01: Atas/Ata_01.md
  - Tainacan:
    - Conheça o Tainacan: Tainacan/home.md
    - Arquitetura Tainacan: Tainacan/Arquitetura.md
    - Guia de contribuição: Tainacan/Guia_De_Contribuicao.md
  - Sprint 0: 
    - Sprint 0 - Planejamento: Sprints/Sprint_0.md
    - Diario de bordo - Mayara: Sprints/Diario_de_Bordo_Mayara.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro

  language: pt-BR
  logo: assets/logo_tainacan.png
  favicon: assets/icon.png

