site_name: GCES- Tainacan
repo_url: https://github.com/
repo_name: GCES- Tainacan

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

nav:
  - Home: index.md
  - Atas:
    - Ata 01: Atas/Ata_01.md
  - Tainacan:
    - Conheça o Tainacan: Tainacan/home.md
    - Arquitetura Tainacan: Tainacan/Arquitetura.md
    - Guia de contribuição: Tainacan/Guia_De_Contribuicao.md
  - Sprint 0:
    - Sprint 0 - Planejamento: Sprints/Sprint-0/Sprint_0.md
    - Sprint 0 - Dificuldades: Sprints/Sprint-0/Sprint_0_Dificuldades.md
    - Diário de bordo - Alexandre: Sprints/Sprint-0/Diario_de_Bordo_Alexandre_Junior.md
    - Diário de bordo - Danilo: Sprints/Sprint-0/Diario_de_Bordo_Danilo.md
    - Diário de bordo - Julia: Sprints/Sprint-0/Diario_de_Bordo_Julia.md
    - Diário de bordo - Mayara: Sprints/Sprint-0/Diario_de_Bordo_Mayara.md
    - Diário de bordo - Marco: Sprints/Sprint-0/Diario_de_Bordo_Marco.md
    - Diário de bordo - Raquel: Sprints/Sprint-0/Diario_de_Bordo_Raquel.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro

  language: pt-BR
  logo: assets/logo_tainacan.png
  favicon: assets/icon.png

